

name: Main

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Version Increment
      uses: reecetech/version-increment@2023.9.3
    - name: Release
      uses: softprops/action-gh-release@v1
