name: Auto Increment Tag

on:
  push:
    branches:
      - main  # Replace 'main' with your desired branch

jobs:
  auto-increment-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the latest tag
        id: get-tag
        run: |
          latest_tag=$(git describe --tags --always $(git rev-list --tags --max-count=1))
          echo "Latest tag: $latest_tag"
          echo "::debug::$latest_tag"
      - name: Increment the tag version
        id: increment-tag
        run: |
          # Extract the major, minor, and patch components from the latest tag
          IFS='.' read -r -a version_parts <<< "${{ steps.get-tag.outputs.latest_tag }}"
          major="${version_parts[0]}" 
          minor="${version_parts[1]}"
          patch="${version_parts[2]}"
          
          echo "::debug::${version_parts[0]}"
          echo "::debug::${version_parts[1]}"
          echo "::debug::${version_parts[2]}"
          
          # Increment the patch version
          patch=$((patch + 1))
          
          # Create the new tag
          new_tag="${major}.${minor}.${patch}"
          echo "::debug::$new_tag"

      - name: Create and push the new tag
        run: |
          git tag ${{ steps.increment-tag.outputs.new_tag }}
          git push origin ${{ steps.increment-tag.outputs.new_tag }}